8. ARPU и p-value

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [3]:
df = pd.read_excel('Данные АБ тестов.xlsx')
df.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [14]:
group_sizes = df.groupby(['experiment_num', 'experiment_group']).size().reset_index(name='user_count')
print("Количество пользователей по группам:\n")
print(group_sizes)

Количество пользователей по группам:

   experiment_num experiment_group  user_count
0               1          control         465
1               1             test         480
2               2          control         465
3               2             test         480
4               3          control         465
5               3             test         480

In [28]:
for i in [1, 2, 3]:
    print(f"\nЭксперимент {i}")
    exp_data = df[df['experiment_num'] == i]
    control_rev = exp_data[exp_data['experiment_group'] == 'control']['revenue']
    test_rev = exp_data[exp_data['experiment_group'] == 'test']['revenue']
    
    _, p_shapiro_ctrl = stats.shapiro(control_rev)
    _, p_shapiro_test = stats.shapiro(test_rev)
    
    print(f"[Шапиро-Уилк] p-value Контроль: {p_shapiro_ctrl:.6f}")
    print(f"[Шапиро-Уилк] p-value Тест:     {p_shapiro_test:.6f}")
    
    if p_shapiro_ctrl < 0.05 or p_shapiro_test < 0.05:
        print("Результат: Распределения не нормальные.")
    else:
        print("Результат: Распределения нормальные.")
        
    stat_mw, p_value_mw = stats.mannwhitneyu(test_rev, control_rev, alternative='two-sided')
    print(f"[Манн-Уитни]  p-value:          {p_value_mw:.6f}")
    
    if p_value_mw < 0.05:
        print("Результат: Различия в распределениях статистически значимы.")
    else:
        print("Результат: Различия незначимы.")

Эксперимент 1
[Шапиро-Уилк] p-value Контроль: 0.000000
[Шапиро-Уилк] p-value Тест:     0.000000
Результат: Распределения не нормальные.
[Манн-Уитни]  p-value:          0.796006
Результат: Различия незначимы.

Эксперимент 2
[Шапиро-Уилк] p-value Контроль: 0.000000
[Шапиро-Уилк] p-value Тест:     0.000000
Результат: Распределения не нормальные.
[Манн-Уитни]  p-value:          0.008453
Результат: Различия в распределениях статистически значимы.

Эксперимент 3
[Шапиро-Уилк] p-value Контроль: 0.000000
[Шапиро-Уилк] p-value Тест:     0.000000
Результат: Распределения не нормальные.
[Манн-Уитни]  p-value:          0.001001
Результат: Различия в распределениях статистически значимы.

9. По датасету с листерами посчитайте средний доход на пользователя

In [29]:
df = pd.read_excel('Листеры.xlsx')
df.head()

   user_id       date  cnt_adverts  age  cnt_contacts  revenue
0      100 2022-01-01            6   21           119       53
1      100 2022-01-02            2   21           200       18
2      100 2022-01-03            6   21           193       42
3      100 2022-01-04            2   21           143       38
4      100 2022-01-05            2   21           190       40

In [30]:
arpu = df['revenue'].sum() / df['user_id'].nunique()
print(arpu)

156.48387096774192

In [31]:
median_age = df.drop_duplicates(subset=['user_id'])['age'].median()
print(median_age)

28.0

In [43]:
A, clicks_A = 100047501, 1003
B, clicks_B = 100001055, 1099

CR_A = clicks_A / A * 100
CR_B = clicks_B / B * 100

print(f"Конверсия группы А: {CR_A:.6f}%")
print(f"Конверсия группы B: {CR_B:.6f}%")

Конверсия группы А: 0.001003%
Конверсия группы B: 0.001099%